name: pre-commit

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set msg
      run: echo "welcome"
    # Intentional fail step for testing purposes
    - name: fail check
      run: exit 1